# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cjK1OlBbYm5G0RNMII__XQvlwXOqReBU
"""

print("ozz")

a = 5
if a == 5:
  print("ozz")
else:
  print("ogg")

sözlük = {"yes" : "evet", "no" : "hayır" }
print ({"yes"})

a = [7,6,5,4,3,2]
print(type(a))
b = a.remove(2)
print(b)

